name: Simulate Parking (Headless)

on:
  pull_request:
  push:
    branches: [ main, master ]

jobs:
  simulate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run simulator (headless)
        env:
          SDL_VIDEODRIVER: dummy
          SDL_AUDIODRIVER: dummy
        run: |
          python main.py
          ls -al

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: parking_result
          path: parking_result.png
          if-no-files-found: warn